spring:
   datasource:   
      url: jdbc:mysql://localhost:3306/olx-advertises
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      generate-ddl: true
      show-sql: true
      
      
      hibernate.ddl-auto: none
      properties:
          hibernate:
             dialect:org.hibernate.dialect.MySQL8Dialect
